[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm install",
    "cd server && npm install",
    "cd client && npm install"
]

[phases.build]
cmds = [
    "cd server && npx prisma generate",
    "cd client && npm run build",
    "ls -la client/dist",
    "echo 'Client build completed successfully'"
]

[start]
cmd = "cd server && NODE_ENV=production node init-db.js"