[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "sqlite"]

[phases.install]
cmds = [
    "npm install",
    "cd server && npm install",
    "cd client && npm install"
]

[phases.build]
cmds = [
    "cd server && node prisma-init.js",
    "cd client && npm run build"
]

[start]
cmd = "cd server && NODE_ENV=production npx tsx src/index.ts"