[build]
builder = "nixpacks"
buildCommand = "npm run install:all && cd server && npx prisma generate"

[deploy]  
startCommand = "cd server && npx tsx src/index.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3